[platformio]
default_envs = esp32dev

[common]
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED@^3.6.0
    knolleary/PubSubClient@^2.8

[env:esp32dev]
platform = espressif32
board = esp32dev
extends = common

[env:esp32c6]
platform = espressif32
board = esp32-c6-devkitc-1
extends = common
